import { missionSchema, observationSchema } from "../src/lib/mission-domain";
export const spec = missionSchema.parse({
  version: 1,
  objective: "FIXTURE cooking educators only",
  platform: "instagram",
  minFollowers: 10000,
  maxFollowers: 500000,
  language: "English",
  requireNoLink: true,
  freshnessHours: 72,
  postedWithinDays: 30,
  targetCount: 20,
  reviewLimit: 20,
  draftLimit: 5,
  budgetNanos: 1000000,
  currency: "USD",
  source: "user_import",
  query: "",
  productConcept: "",
  autonomy: "research",
});
export const observed = observationSchema.parse({
  handle: "fixture_creator",
  sourceUrl: "https://example.test/fixture_creator",
  observedAt: "2026-09-29T10:00:00Z",
  followers: 20000,
  exactFollowers: true,
  bioLinks: "ABSENT_VERIFIED",
  allLinkFieldsChecked: true,
  language: "English",
  lastPostAt: "2026-09-28T10:00:00Z",
  teachingTopic: "repeatable knife skills",
  contentExcerpt: "Practice equal cuts slowly before increasing speed.",
  contentUrl: "https://example.test/lesson",
  method: "human_observation",
  rightsAttested: true,
  adultStatus: "adult",
  offers: "Unknown",
});
