import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowRight, Check, Clock3, Copy, ExternalLink, Inbox, MessageSquareText, Plus, Send, Target, Users, Zap } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth";
import { useWorkspace } from "@/lib/workspace";
import { leadStage, fetchNotes, formatWhen, STATUSES, updateLeadStatus, type Lead, type LeadStatus } from "@/lib/crm";
import { EMAIL_SEQUENCE, SUBJECT_LINES } from "@/lib/email-templates";
import { Button } from "@/components/ui/button";
import { LeadAvatar } from "./LeadAvatar";
import { LeadBoard } from "./LeadBoard";
import { StatusPill } from "./StatusPill";
import { EmptyState, ErrorState, TableSkeleton } from "./WorkspaceState";
import { cn } from "@/lib/utils";

export function PageHeader({ title, description, actions }: { title: string; description: string; actions?: React.ReactNode }) {
  return <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{actions ? <div className="flex gap-2">{actions}</div> : null}</header>;
}

function useStatusMutation() {
  const { user } = useAuth(); const queryClient = useQueryClient();
  return useMutation({ mutationFn: ({ ids, status }: { ids: string[]; status: LeadStatus }) => updateLeadStatus(ids, status, user?.id ?? ""), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["leads"] }); toast.success("Lead updated"); }, onError: () => toast.error("Couldn't update this lead. Try again.") });
}

export function DashboardPage() {
  const { user } = useAuth();
  const { leads, profiles, isLoading, error, setAddLeadOpen, setActiveLead } = useWorkspace();
  const profile = profiles.find((item) => item.id === user?.id);
  const mutation = useStatusMutation();
  const now = Date.now();
  const followups = leads.filter((lead) => leadStage(lead) === "contacted" && lead.last_touched_at && now - new Date(lead.last_touched_at).getTime() > 2 * 86400000);
  const replies = leads.filter((lead) => leadStage(lead) === "replied");
  const newLeads = leads.filter((lead) => leadStage(lead) === "not_contacted");
  const deals = leads.filter((lead) => leadStage(lead) === "deal");
  const queue = [...replies, ...followups, ...newLeads].slice(0, 7);
  const counts = Object.fromEntries(STATUSES.map((item) => [item.value, leads.filter((lead) => leadStage(lead) === item.value).length])) as Record<LeadStatus, number>;
  if (isLoading) return <Page><TableSkeleton /></Page>;
  if (error) return <Page><ErrorState /></Page>;
  return <Page>
    <PageHeader title={`Good ${greeting()}, ${profile?.display_name?.split(" ")[0] ?? "there"}`} description="Here's what needs your attention today." actions={<><Button variant="outline" onClick={() => setAddLeadOpen(true)}><Plus />Add lead</Button><Button asChild><Link to="/outreach"><Zap />Start outreach</Link></Button></>} />
    <section className="mt-7"><SectionTitle title="Today's priorities" /><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Priority icon={<Clock3 />} label="Follow-ups due" value={followups.length} tone="warning" to="/follow-ups" /><Priority icon={<Inbox />} label="Replies" value={replies.length} tone="violet" to="/replies" /><Priority icon={<Users />} label="New leads" value={newLeads.length} to="/leads" /><Priority icon={<Target />} label="Deals" value={deals.length} tone="success" to="/pipeline" /></div></section>
    <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.7fr)]">
      <section><SectionTitle title="Today's work queue" action={<Link to="/outreach" className="text-xs font-medium text-primary hover:underline">Open full queue</Link>} /><div className="overflow-hidden rounded-lg border border-border bg-card">{queue.map((lead) => <div key={lead.id} className="group flex min-h-14 items-center gap-3 border-b border-border px-3 py-2 last:border-0 hover:bg-secondary/50"><LeadAvatar username={lead.username} /><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">@{lead.username.replace(/^@/, "")}</p><p className="truncate text-xs text-muted-foreground">{leadStage(lead) === "replied" ? "New reply" : leadStage(lead) === "contacted" ? `Follow up · ${formatWhen(lead.last_touched_at)}` : lead.match_note || "Ready to contact"}</p></div><StatusPill status={leadStage(lead)} /><Button variant="ghost" size="sm" onClick={() => setActiveLead(lead)}>Open</Button>{leadStage(lead) !== "replied" ? <Button size="sm" onClick={() => mutation.mutate({ ids: [lead.id], status: leadStage(lead) === "not_contacted" ? "contacted" : "replied" })}>{leadStage(lead) === "not_contacted" ? "Start" : "Complete"}</Button> : null}</div>)}{queue.length === 0 ? <EmptyState title="Queue is clear" description="There are no leads needing attention right now." /> : null}</div></section>
      <section><SectionTitle title="Recent activity" /><div className="rounded-lg border border-border bg-card px-4">{leads.filter((lead) => lead.last_touched_at).sort((a,b) => (b.last_touched_at ?? "").localeCompare(a.last_touched_at ?? "")).slice(0, 7).map((lead) => <button key={lead.id} onClick={() => setActiveLead(lead)} className="flex w-full items-start gap-3 border-b border-border py-3 text-left last:border-0"><span className="mt-0.5 flex size-7 items-center justify-center rounded-full bg-secondary text-muted-foreground"><Activity className="size-3.5" /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs"><strong>@{lead.username.replace(/^@/, "")}</strong> moved to {leadStage(lead).replace("_", " ")}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{formatWhen(lead.last_touched_at)}</span></span></button>)}</div></section>
    </div>
    <section className="mt-7"><SectionTitle title="Pipeline" action={<Link to="/pipeline" className="text-xs font-medium text-primary hover:underline">View pipeline</Link>} /><div className="grid grid-cols-2 overflow-hidden rounded-lg border border-border bg-card sm:grid-cols-5">{STATUSES.map((item) => <Link key={item.value} to="/leads" className="border-r border-border px-4 py-3 last:border-0 hover:bg-secondary/50"><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className={cn("size-2 rounded-full", item.dot)} />{item.label}</span><strong className="mt-1 block text-lg tabular-nums">{counts[item.value].toLocaleString()}</strong><span className="text-[11px] text-muted-foreground">{leads.length ? Math.round(counts[item.value] / leads.length * 100) : 0}% of total</span></Link>)}</div></section>
  </Page>;
}

export function OutreachPage() {
  const { leads, setActiveLead } = useWorkspace(); const mutation = useStatusMutation();
  const queue = leads.filter((lead) => leadStage(lead) === "not_contacted"); const [index, setIndex] = useState(0); const [message, setMessage] = useState("Hey — I came across your Instagram and loved your work. I’d like to explore a potential collaboration. Open to chatting?");
  const lead = queue[index];
  if (!lead) return <Page><PageHeader title="Outreach" description="Work through new prospects without losing momentum." /><EmptyState title="Outreach queue complete" description="Every available lead has been contacted." /></Page>;
  return <Page><PageHeader title="Outreach" description={`${queue.length.toLocaleString()} leads ready to contact.`} />
    <div className="mt-6 grid min-h-[calc(100vh-190px)] overflow-hidden rounded-lg border border-border bg-card xl:grid-cols-[260px_minmax(320px,1fr)_minmax(360px,0.9fr)]">
      <aside className="hidden border-r border-border xl:block"><div className="border-b border-border px-4 py-3 text-xs font-semibold">Queue · {index + 1} of {queue.length}</div><div className="max-h-[calc(100vh-240px)] overflow-y-auto">{queue.slice(index, index + 25).map((item, offset) => <button key={item.id} onClick={() => setIndex(index + offset)} className={cn("flex w-full items-center gap-2 border-b border-border px-3 py-2.5 text-left hover:bg-secondary", item.id === lead.id && "bg-accent")}><LeadAvatar username={item.username} size="sm" /><span className="min-w-0"><span className="block truncate text-xs font-medium">@{item.username.replace(/^@/, "")}</span><span className="block truncate text-[11px] text-muted-foreground">{item.email ?? "Instagram"}</span></span></button>)}</div></aside>
      <section className="flex flex-col justify-between p-6"><div><LeadAvatar username={lead.username} size="lg" /><h2 className="mt-4 text-xl font-semibold">@{lead.username.replace(/^@/, "")}</h2><p className="mt-1 text-sm text-muted-foreground">Instagram prospect · #{lead.number}</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Email" value={lead.email ?? "Not available"} /><Info label="Stage" value="Not contacted" /></div>{lead.match_note ? <div className="mt-6 border-t border-border pt-5"><p className="text-xs font-semibold">Why selected</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{lead.match_note}</p></div> : null}</div><div className="mt-6 flex gap-2"><Button variant="outline" onClick={() => setActiveLead(lead)}>Open details</Button>{lead.instagram_url ? <Button variant="outline" asChild><a href={lead.instagram_url} target="_blank" rel="noreferrer">Instagram <ExternalLink /></a></Button> : null}</div></section>
      <section className="border-t border-border bg-secondary/25 p-5 xl:border-l xl:border-t-0"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Message</h3><span className="text-xs text-muted-foreground">Direct message</span></div><select className="mt-4 h-9 w-full rounded-md border border-input bg-card px-3 text-sm"><option>Friendly introduction</option><option>Collaboration pitch</option></select><textarea value={message} onChange={(event) => setMessage(event.target.value)} className="mt-3 min-h-52 w-full resize-none rounded-lg border border-input bg-card p-3 text-sm leading-6 outline-none focus:ring-2 focus:ring-ring/30" /><div className="mt-3 flex gap-2"><Button variant="outline" onClick={() => { navigator.clipboard.writeText(message); toast.success("Message copied"); }}><Copy />Copy</Button><Button className="flex-1" onClick={() => mutation.mutate({ ids: [lead.id], status: "contacted" }, { onSuccess: () => setIndex((value) => Math.min(value, queue.length - 2)) })}><Send />Mark sent & next</Button></div></section>
    </div></Page>;
}

export function FollowUpsPage() {
  const { leads, setActiveLead } = useWorkspace(); const mutation = useStatusMutation(); const now = Date.now();
  const rows = leads.filter((lead) => leadStage(lead) === "contacted").sort((a,b) => (a.last_touched_at ?? "").localeCompare(b.last_touched_at ?? ""));
  const overdue = rows.filter((lead) => lead.last_touched_at && now - new Date(lead.last_touched_at).getTime() > 3 * 86400000);
  return <Page><PageHeader title="Follow-ups" description="Reconnect with contacted leads that have not replied." /><QueueSection title={`Overdue · ${overdue.length}`} rows={overdue} onOpen={setActiveLead} onDone={(lead) => mutation.mutate({ ids: [lead.id], status: "replied" })} /><QueueSection title={`Upcoming · ${rows.length - overdue.length}`} rows={rows.filter((lead) => !overdue.includes(lead))} onOpen={setActiveLead} onDone={(lead) => mutation.mutate({ ids: [lead.id], status: "replied" })} /></Page>;
}

export function RepliesPage() {
  const { leads, ownerName, setActiveLead } = useWorkspace(); const mutation = useStatusMutation(); const replies = leads.filter((lead) => leadStage(lead) === "replied"); const [active, setActive] = useState<Lead | null>(replies[0] ?? null);
  const notes = useQuery({ queryKey: ["lead-notes", active?.id], queryFn: () => fetchNotes(active?.id ?? ""), enabled: Boolean(active) });
  return <Page><PageHeader title="Replies" description="Review responses and move conversations forward." />{replies.length === 0 ? <EmptyState title="No replies yet" description="Leads marked as replied will appear here." /> : <div className="mt-6 grid min-h-[calc(100vh-190px)] overflow-hidden rounded-lg border border-border bg-card lg:grid-cols-[300px_minmax(0,1fr)_280px]"><aside className="border-r border-border">{replies.map((lead) => <button key={lead.id} onClick={() => setActive(lead)} className={cn("flex w-full items-center gap-3 border-b border-border p-3 text-left hover:bg-secondary", active?.id === lead.id && "bg-accent")}><LeadAvatar username={lead.username} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">@{lead.username.replace(/^@/, "")}</span><span className="block truncate text-xs text-muted-foreground">{lead.match_note ?? "Reply needs review"}</span></span><span className="text-[11px] text-muted-foreground">{formatWhen(lead.last_touched_at)}</span></button>)}</aside><section className="p-6">{active ? <><h2 className="text-base font-semibold">Conversation with @{active.username.replace(/^@/, "")}</h2><div className="mt-6 space-y-3">{(notes.data ?? []).length ? (notes.data ?? []).map((note) => <div key={note.id} className="max-w-[80%] rounded-lg border border-border bg-secondary/50 p-3"><p className="text-sm leading-6">{note.body}</p><p className="mt-2 text-[11px] text-muted-foreground">{ownerName(note.author_id)} · {formatWhen(note.created_at)}</p></div>) : <EmptyState title="No messages recorded" description="Add conversation context from the lead drawer." action="Open lead" onAction={() => setActiveLead(active)} />}</div></> : null}</section>{active ? <aside className="border-l border-border p-4"><LeadAvatar username={active.username} size="lg" /><h3 className="mt-3 font-semibold">@{active.username.replace(/^@/, "")}</h3><p className="text-xs text-muted-foreground">{active.email ?? "No email"}</p><div className="mt-5"><Info label="Owner" value={ownerName(active.owner_id)} /><div className="mt-4"><Info label="Stage" value="Replied" /></div></div><div className="mt-6 grid gap-2"><Button onClick={() => mutation.mutate({ ids: [active.id], status: "deal" })}><Check />Move to deal</Button><Button variant="outline" onClick={() => mutation.mutate({ ids: [active.id], status: "dead" })}>Mark not interested</Button></div></aside> : null}</div>}</Page>;
}

export function PipelinePage() { const { leads, ownerName, setActiveLead } = useWorkspace(); const mutation = useStatusMutation(); return <Page><PageHeader title="Pipeline" description="Move opportunities through every stage." /><div className="mt-6"><LeadBoard leads={leads} ownerName={ownerName} onOpen={setActiveLead} onStatusChange={(ids, status) => mutation.mutate({ ids, status })} /></div></Page>; }

export function AnalyticsPage() {
  const { leads, profiles } = useWorkspace(); const [range, setRange] = useState("30D");
  const contacted = leads.filter((lead) => leadStage(lead) !== "not_contacted").length; const replies = leads.filter((lead) => leadStage(lead) === "replied" || leadStage(lead) === "deal").length; const deals = leads.filter((lead) => leadStage(lead) === "deal").length;
  const metrics = [{ label: "Outreach sent", value: contacted }, { label: "Replies", value: replies }, { label: "Reply rate", value: `${contacted ? Math.round(replies / contacted * 100) : 0}%` }, { label: "Deals", value: deals }, { label: "Conversion", value: `${contacted ? Math.round(deals / contacted * 100) : 0}%` }];
  const days = Array.from({ length: 14 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() - 13 + index); const key = day.toISOString().slice(0,10); return { label: day.toLocaleDateString(undefined, { weekday: "short" }), value: leads.filter((lead) => lead.last_touched_at?.startsWith(key)).length }; }); const peak = Math.max(1, ...days.map((day) => day.value));
  return <Page><PageHeader title="Analytics" description="Understand outreach performance and pipeline health." actions={<div className="flex rounded-md border border-input bg-card p-0.5">{["7D","30D","90D"].map((item) => <Button key={item} size="sm" variant={range === item ? "secondary" : "ghost"} onClick={() => setRange(item)}>{item}</Button>)}</div>} /><div className="mt-6 grid grid-cols-2 overflow-hidden rounded-lg border border-border bg-card lg:grid-cols-5">{metrics.map((metric) => <div key={metric.label} className="border-r border-border p-4 last:border-0"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{typeof metric.value === "number" ? metric.value.toLocaleString() : metric.value}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-lg border border-border bg-card p-5"><h2 className="text-sm font-semibold">Outreach activity</h2><p className="mt-1 text-xs text-muted-foreground">Lead updates over the last 14 days</p><div className="mt-8 flex h-52 items-end gap-2">{days.map((day) => <div key={day.label} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] tabular-nums text-muted-foreground">{day.value || ""}</span><div className="w-full max-w-8 rounded-t bg-primary/80" style={{ height: `${Math.max(3, day.value / peak * 150)}px` }} /><span className="text-[10px] text-muted-foreground">{day.label.slice(0,1)}</span></div>)}</div></section><section className="rounded-lg border border-border bg-card p-5"><h2 className="text-sm font-semibold">Team performance</h2><div className="mt-4 space-y-4">{profiles.map((profile) => { const owned = leads.filter((lead) => lead.owner_id === profile.id); const won = owned.filter((lead) => leadStage(lead) === "deal").length; return <div key={profile.id}><div className="flex items-center justify-between text-xs"><span>{profile.display_name}</span><span className="tabular-nums text-muted-foreground">{owned.length} touched · {won} deals</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-primary" style={{ width: `${Math.max(2, contacted ? owned.length / contacted * 100 : 0)}%` }} /></div></div>; })}</div></section></div></Page>;
}

export function TemplatesPage() {
  const [step, setStep] = useState(1);
  const [variant, setVariant] = useState(0);
  const current = EMAIL_SEQUENCE.find((item) => item.step === step) ?? EMAIL_SEQUENCE[0]!;
  const body = current.variants[Math.min(variant, current.variants.length - 1)] ?? "";
  return <Page>
    <PageHeader title="Templates" description="The full 7-email outreach sequence, ready to copy." actions={<Button onClick={() => { void navigator.clipboard.writeText(body); toast.success("Email copied"); }}><MessageSquareText />Copy email</Button>} />
    <div className="mt-6 grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]">
      <div className="space-y-1">
        {EMAIL_SEQUENCE.map((item) => <button key={item.step} onClick={() => { setStep(item.step); setVariant(0); }} className={`w-full rounded-md border px-3 py-2 text-left text-[13px] ${item.step === step ? "border-primary/40 bg-secondary font-medium" : "border-border hover:bg-secondary/60"}`}>Email {item.step}<span className="mt-0.5 block text-[11px] font-normal text-muted-foreground">Reply keyword: {item.keyword}</span></button>)}
      </div>
      <div className="space-y-4">
        <div className="rounded-lg border border-border bg-card p-4">
          <p className="text-sm font-medium">Email {current.step}</p>
          <p className="mt-1 text-xs text-muted-foreground">{current.purpose}</p>
          <div className="mt-3 flex flex-wrap gap-1.5">{current.variants.map((_, index) => <button key={index} onClick={() => setVariant(index)} className={`h-7 rounded-md border px-2.5 text-xs ${index === variant ? "border-primary/40 bg-secondary font-medium" : "border-border hover:bg-secondary/60"}`}>v{index + 1}</button>)}</div>
          <pre className="mt-4 whitespace-pre-wrap font-sans text-[13px] leading-6">{body}</pre>
        </div>
        <div className="rounded-lg border border-border bg-card p-4">
          <h2 className="text-sm font-semibold">Subject lines</h2>
          <div className="mt-3 grid gap-1.5 sm:grid-cols-2">{SUBJECT_LINES.map((line) => <button key={line} onClick={() => { void navigator.clipboard.writeText(line); toast.success("Subject copied"); }} className="truncate rounded-md border border-border px-2.5 py-1.5 text-left text-xs hover:bg-secondary/60">{line}</button>)}</div>
        </div>
      </div>
    </div>
  </Page>;
}

export function SettingsPage() { const { user } = useAuth(); const { profiles } = useWorkspace(); const profile = profiles.find((item) => item.id === user?.id); return <Page><PageHeader title="Settings" description="Manage your workspace preferences and account." /><div className="mt-6 max-w-2xl overflow-hidden rounded-lg border border-border bg-card"><div className="border-b border-border p-5"><h2 className="text-sm font-semibold">Profile</h2><p className="mt-1 text-xs text-muted-foreground">Your identity across the shared workspace.</p></div><dl className="grid gap-5 p-5 sm:grid-cols-2"><Info label="Display name" value={profile?.display_name ?? "Workspace member"} /><Info label="Email" value={user?.email ?? "—"} /><Info label="Workspace access" value="Team member" /><Info label="Realtime sync" value="Connected" /></dl></div></Page>; }

function Page({ children }: { children: React.ReactNode }) { return <div className="mx-auto max-w-[1800px] px-4 py-5 lg:px-6">{children}</div>; }
function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="mb-2.5 flex items-center justify-between"><h2 className="text-sm font-semibold">{title}</h2>{action}</div>; }
function Priority({ icon, label, value, tone = "neutral", to }: { icon: React.ReactNode; label: string; value: number; tone?: "neutral" | "warning" | "violet" | "success"; to: "/leads" | "/replies" | "/follow-ups" | "/pipeline" }) { return <Link to={to} className="group flex items-center gap-3 rounded-lg border border-border bg-card p-3 hover:border-input hover:shadow-panel"><span className={cn("flex size-9 items-center justify-center rounded-md bg-secondary text-muted-foreground [&>svg]:size-4", tone === "warning" && "bg-warning-soft text-warning", tone === "violet" && "bg-status-replied-soft text-status-replied", tone === "success" && "bg-success-soft text-success")}>{icon}</span><span className="min-w-0 flex-1"><span className="block text-xs text-muted-foreground">{label}</span><strong className="block text-lg tabular-nums">{value.toLocaleString()}</strong></span><ArrowRight className="size-4 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" /></Link>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>; }
function QueueSection({ title, rows, onOpen, onDone }: { title: string; rows: Lead[]; onOpen: (lead: Lead) => void; onDone: (lead: Lead) => void }) { return <section className="mt-7"><SectionTitle title={title} />{rows.length ? <div className="overflow-hidden rounded-lg border border-border bg-card">{rows.map((lead) => <div key={lead.id} className="flex items-center gap-3 border-b border-border p-3 last:border-0"><LeadAvatar username={lead.username} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">@{lead.username.replace(/^@/, "")}</p><p className="text-xs text-muted-foreground">Last contacted {formatWhen(lead.last_touched_at)} · no reply recorded</p></div><Button variant="ghost" size="sm" onClick={() => onOpen(lead)}>Open</Button><Button variant="outline" size="sm" onClick={() => toast.success("Snoozed for tomorrow")}>Snooze</Button><Button size="sm" onClick={() => onDone(lead)}><Check />Done</Button></div>)}</div> : <div className="rounded-lg border border-dashed border-border bg-card"><EmptyState title="Nothing here" description="No leads currently need attention in this group." /></div>}</section>; }
function greeting() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }